extern const GeoLayout glider_geo[];
extern Lights1 glider_color_lights;
extern Lights1 glider_white_lights;
extern Vtx glider_glider_mesh_layer_1_vtx_0[22];
extern Gfx glider_glider_mesh_layer_1_tri_0[];
extern Vtx glider_glider_mesh_layer_1_vtx_1[96];
extern Gfx glider_glider_mesh_layer_1_tri_1[];
extern Gfx mat_glider_color[];
extern Gfx mat_glider_white[];
extern Gfx glider_glider_mesh_layer_1[];
extern Gfx glider_material_revert_render_settings[];
